
--PARAMS OTC_T_360_UBICACION ---------PRODUCCION
DELETE FROM params_des WHERE entidad='D_OTC_T_360_UBICACION';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_UBICACION','RUTA','/RGenerator/reportes/Cliente360',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_UBICACION','RUTA_LOG','/RGenerator/reportes/Cliente360',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_UBICACION','SHELL','/RGenerator/reportes/Cliente360/Bin/OTC_T_360_UBICACION.sh',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_UBICACION','LIMPIAR','1',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_UBICACION','RUTA','/DesarrolloTI/RGenerator/reportes/Cliente360',0,0);
SELECT * FROM params_des WHERE ENTIDAD='D_OTC_T_360_UBICACION';





--PARAMS D_OTC_T_360_UBICACION "REINGENIERIA"---------DESARROLLO
DELETE FROM params_des WHERE entidad='D_OTC_T_360_UBICACION';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_UBICACION','VAL_USER','nae108834',0,0);
SELECT * FROM params_des WHERE ENTIDAD='D_OTC_T_360_UBICACION';