# T: Tabla
# D: Date
# I: Integer
# S: String

# N 01
def qry_ori_otc_t_alta_baja_hist(vTAltBajHist):
    qry='''
SELECT
	TIPO
	, TELEFONO
	, FECHA
	, CANAL
	, SUB_CANAL
	, NUEVO_SUB_CANAL
	, PORTABILIDAD
	, Operadora_origen
	, Operadora_destino
	, motivo
	, DISTRIBUIDOR
	, OFICINA
FROM
	{vTAltBajHist}
    '''.format(vTAltBajHist=vTAltBajHist)
    return qry

def qry_insrt_otc_t_alta_baja_hist_alta(vTAltBI, fecha_movimientos_cp):
    qry='''
SELECT
	'ALTA' AS TIPO
	, TELEFONO
	, FECHA_ALTA AS FECHA
	, CANAL_COMERCIAL AS CANAL
	, SUB_CANAL
	, CAST( NULL AS STRING) AS NUEVO_SUB_CANAL
	, PORTABILIDAD
	, Operadora_origen
	, 'MOVISTAR (OTECEL)' AS Operadora_destino
	, CAST( NULL AS STRING) AS motivo
	, NOM_DISTRIBUIDOR AS DISTRIBUIDOR
	, OFICINA
FROM
	{vTAltBI}
WHERE
	p_FECHA_PROCESO = '{fecha_movimientos_cp}'
	AND marca = 'TELEFONICA'
    '''.format(vTAltBI=vTAltBI, fecha_movimientos_cp=fecha_movimientos_cp)
    return qry

# N 02

def qry_insrt_otc_t_alta_baja_hist_baja(vTBajBI, fecha_movimientos_cp):
    qry='''
SELECT
	'BAJA' AS TIPO
	, TELEFONO
	, FECHA_BAJA AS FECHA
	, CAST( NULL AS STRING) AS CANAL
	, CAST( NULL AS STRING) AS SUB_CANAL
	, CAST( NULL AS STRING) AS NUEVO_SUB_CANAL
	, PORTABILIDAD
	, 'MOVISTAR (OTECEL)' AS Operadora_origen
	, Operadora_destino
	, MOTIVO_BAJA AS motivo
	, CAST( NULL AS STRING) AS DISTRIBUIDOR
	, CAST( NULL AS STRING) AS OFICINA
FROM
	{vTBajBI}
WHERE
	p_FECHA_PROCESO = '{fecha_movimientos_cp}'
	AND marca = 'TELEFONICA'
    '''.format(vTBajBI=vTBajBI, fecha_movimientos_cp=fecha_movimientos_cp)
    return qry


# N03
def qry_ori_otc_t_transfer_hist(vTTransfHist):
    qry='''
SELECT
	TIPO
	, TELEFONO
	, FECHA
	, CANAL
	, SUB_CANAL
	, NUEVO_SUB_CANAL
	, DISTRIBUIDOR
	, OFICINA
FROM
	{vTTransfHist}
    '''.format(vTTransfHist=vTTransfHist)
    return qry


def qry_insrt_otc_t_transfer_hist_pre_pos(vTTrInBI, fecha_movimientos_cp):
    qry='''
SELECT
	'PRE_POS' AS TIPO
	, TELEFONO
	, FECHA_TRANSFERENCIA AS FECHA
	, CANAL_USUARIO AS CANAL
	, SUB_CANAL
	, CAST( NULL AS STRING) AS NUEVO_SUB_CANAL
	, NOM_DISTRIBUIDOR_USUARIO AS DISTRIBUIDOR
	, OFICINA_USUARIO AS OFICINA
FROM
	{vTTrInBI}
WHERE
	p_FECHA_PROCESO = '{fecha_movimientos_cp}'
    '''.format(vTTrInBI=vTTrInBI, fecha_movimientos_cp=fecha_movimientos_cp)
    return qry

# N 04

def qry_insrt_otc_t_transfer_hist_pos_pre(vTTrOutBI, fecha_movimientos_cp):
    qry='''
SELECT
	'POS_PRE' AS TIPO
	, TELEFONO
	, FECHA_TRANSFERENCIA AS FECHA
	, CANAL_USUARIO AS CANAL
	, SUB_CANAL
	, CAST( NULL AS STRING) AS NUEVO_SUB_CANAL
	, NOM_DISTRIBUIDOR_USUARIO AS DISTRIBUIDOR
	, OFICINA_USUARIO AS OFICINA
FROM
	{vTTrOutBI}
WHERE
	p_FECHA_PROCESO = '{fecha_movimientos_cp}'
    '''.format(vTTrOutBI=vTTrOutBI, fecha_movimientos_cp=fecha_movimientos_cp)
    return qry


# N 5
def qry_ori_otc_t_cambio_plan_hist(vTCPHist):
    qry='''
SELECT
	TIPO
	, TELEFONO
	, FECHA
	, CANAL
	, SUB_CANAL
	, NUEVO_SUB_CANAL
	, DISTRIBUIDOR
	, OFICINA
	, COD_PLAN_ANTERIOR
	, DES_PLAN_ANTERIOR
	, TB_DESCUENTO
	, TB_OVERRIDE
	, DELTA
FROM
	{vTCPHist}
    '''.format(vTCPHist=vTCPHist)
    return qry


def qry_insrt_otc_t_cambio_plan_hist(vTCPBI, fecha_movimientos_cp):
    qry='''
SELECT
	TIPO_MOVIMIENTO AS TIPO
	, TELEFONO
	, FECHA_CAMBIO_PLAN AS FECHA
	, CANAL
	, SUB_CANAL
	, CAST( NULL AS STRING) AS NUEVO_SUB_CANAL
	, NOM_DISTRIBUIDOR AS DISTRIBUIDOR
	, OFICINA
	, CODIGO_PLAN_ANTERIOR AS COD_PLAN_ANTERIOR
	, DESCRIPCION_PLAN_ANTERIOR AS DES_PLAN_ANTERIOR
	, TARIFA_OV_PLAN_ANT AS TB_DESCUENTO
	, DESCUENTO_TARIFA_PLAN_ANT AS TB_OVERRIDE
	, DELTA AS DELTA
FROM
	{vTCPBI}
WHERE
	p_FECHA_PROCESO = {fecha_movimientos_cp}
    '''.format(vTCPBI=vTCPBI, fecha_movimientos_cp=fecha_movimientos_cp)
    return qry

# N 06

def qry_otc_t_alta_hist_unic(vTAltBajHist, fecha_movimientos):
    qry='''
SELECT
	XX.TIPO
	, XX.TELEFONO
	, XX.FECHA
	, XX.CANAL
	, XX.SUB_CANAL
	, XX.NUEVO_SUB_CANAL
	, XX.PORTABILIDAD
	, XX.Operadora_origen
	, XX.Operadora_destino
	, XX.motivo
	, XX.DISTRIBUIDOR
	, XX.OFICINA
FROM
	(
	SELECT
		AA.TIPO
		, AA.TELEFONO
		, AA.FECHA
		, AA.CANAL
		, AA.SUB_CANAL
		, AA.NUEVO_SUB_CANAL
		, AA.PORTABILIDAD
		, AA.Operadora_origen
		, AA.Operadora_destino
		, AA.motivo
		, AA.DISTRIBUIDOR
		, AA.OFICINA
		, ROW_NUMBER() OVER (PARTITION BY aa.TIPO
		, aa.TELEFONO
	ORDER BY
		aa.FECHA DESC) AS RNUM
	FROM
		{vTAltBajHist} AS AA
	WHERE
		FECHA <'{fecha_movimientos}'
		AND TIPO = 'ALTA'
) XX
WHERE
	XX.rnum = 1
    '''.format(vTAltBajHist=vTAltBajHist, fecha_movimientos=fecha_movimientos)
    return qry

# N07
def qry_otc_t_baja_hist_unic(vTAltBajHist, fecha_movimientos):
    qry='''
SELECT
	XX.TIPO
	, XX.TELEFONO
	, XX.FECHA
	, XX.CANAL
	, XX.SUB_CANAL
	, XX.NUEVO_SUB_CANAL
	, XX.PORTABILIDAD
	, XX.Operadora_origen
	, XX.Operadora_destino
	, XX.motivo
	, XX.DISTRIBUIDOR
	, XX.OFICINA
FROM
	(
	SELECT
		AA.TIPO
		, AA.TELEFONO
		, AA.FECHA
		, AA.CANAL
		, AA.SUB_CANAL
		, AA.NUEVO_SUB_CANAL
		, AA.PORTABILIDAD
		, AA.Operadora_origen
		, AA.Operadora_destino
		, AA.motivo
		, AA.DISTRIBUIDOR
		, AA.OFICINA
		, ROW_NUMBER() OVER (PARTITION BY aa.TIPO
		, aa.TELEFONO
	ORDER BY
		aa.FECHA DESC) AS RNUM
	FROM
		{vTAltBajHist} AS AA
	WHERE
		FECHA <'{fecha_movimientos}'
		AND TIPO = 'BAJA'
) XX
WHERE
	XX.rnum = 1
    '''.format(vTAltBajHist=vTAltBajHist, fecha_movimientos=fecha_movimientos)
    return qry


# N08
def qry_otc_t_pos_pre_hist_unic(vTTransfHist, fecha_movimientos):
    qry='''
SELECT
	XX.TIPO
	, XX.TELEFONO
	, XX.FECHA
	, XX.CANAL
	, XX.SUB_CANAL
	, XX.NUEVO_SUB_CANAL
	, XX.DISTRIBUIDOR
	, XX.OFICINA
FROM
	(
	SELECT
		AA.TIPO
		, AA.TELEFONO
		, AA.FECHA
		, AA.CANAL
		, AA.SUB_CANAL
		, AA.NUEVO_SUB_CANAL
		, AA.DISTRIBUIDOR
		, AA.OFICINA
		, ROW_NUMBER() OVER (PARTITION BY aa.TIPO
		, aa.TELEFONO
	ORDER BY
		aa.FECHA DESC) AS RNUM
	FROM
		{vTTransfHist} AS AA
	WHERE
		FECHA <'{fecha_movimientos}'
		AND TIPO = 'POS_PRE'
) XX
WHERE
	XX.rnum = 1
    '''.format(vTTransfHist=vTTransfHist, fecha_movimientos=fecha_movimientos)
    return qry


# N09
def qry_otc_t_pre_pos_hist_unic(vTTransfHist, fecha_movimientos):
    qry='''
SELECT
	XX.TIPO
	, XX.TELEFONO
	, XX.FECHA
	, XX.CANAL
	, XX.SUB_CANAL
	, XX.NUEVO_SUB_CANAL
	, XX.DISTRIBUIDOR
	, XX.OFICINA
FROM
	(
	SELECT
		AA.TIPO
		, AA.TELEFONO
		, AA.FECHA
		, AA.CANAL
		, AA.SUB_CANAL
		, AA.NUEVO_SUB_CANAL
		, AA.DISTRIBUIDOR
		, AA.OFICINA
		, ROW_NUMBER() OVER (PARTITION BY aa.TIPO
		, aa.TELEFONO
	ORDER BY
		aa.FECHA DESC) AS RNUM
	FROM
		{vTTransfHist} AS AA
	WHERE
		FECHA <'{fecha_movimientos}'
		AND TIPO = 'PRE_POS'
) XX
WHERE
	XX.rnum = 1
    '''.format(vTTransfHist=vTTransfHist, fecha_movimientos=fecha_movimientos)
    return qry


# N10
def qry_otc_t_cambio_plan_hist_unic(vTCPHist, fecha_movimientos):
    qry='''
SELECT
	XX.TIPO
	, XX.TELEFONO
	, XX.FECHA
	, XX.CANAL
	, XX.SUB_CANAL
	, XX.NUEVO_SUB_CANAL
	, XX.DISTRIBUIDOR
	, XX.OFICINA
	, XX.COD_PLAN_ANTERIOR
	, XX.DES_PLAN_ANTERIOR
	, XX.TB_DESCUENTO
	, XX.TB_OVERRIDE
	, XX.DELTA
FROM
	(
	SELECT
		AA.TIPO
		, AA.TELEFONO
		, AA.FECHA
		, AA.CANAL
		, AA.SUB_CANAL
		, AA.NUEVO_SUB_CANAL
		, AA.DISTRIBUIDOR
		, AA.OFICINA
		, AA.COD_PLAN_ANTERIOR
		, AA.DES_PLAN_ANTERIOR
		, AA.TB_DESCUENTO
		, AA.TB_OVERRIDE
		, AA.DELTA
		, ROW_NUMBER() OVER (PARTITION BY aa.TELEFONO
	ORDER BY
		aa.FECHA DESC) AS RNUM
	FROM
		{vTCPHist} AS AA
	WHERE
		FECHA <'{fecha_movimientos}'
) XX
WHERE
	XX.rnum = 1
    '''.format(vTCPHist=vTCPHist, fecha_movimientos=fecha_movimientos)
    return qry



# N11
def qry_otc_t_360_parque_1_tmp_t_mov(vTPivotParq, vTMP06, vTMP08, vTMP09, vTMP10):
    qry='''
SELECT
	NUM_TELEFONICO
	, CODIGO_PLAN
	, FECHA_ALTA
	, FECHA_LAST_STATUS
	, ESTADO_ABONADO
	, FECHA_PROCESO
	, NUMERO_ABONADO
	, LINEA_NEGOCIO
	, ACCOUNT_NUM
	, SUB_SEGMENTO
	, TIPO_DOC_CLIENTE
	, IDENTIFICACION_CLIENTE
	, CLIENTE
	, CUSTOMER_REF
	, COUNTED_DAYS
	, LINEA_NEGOCIO_HOMOLOGADO
	, CATEGORIA_PLAN
	, TARIFA
	, NOMBRE_PLAN
	, MARCA
	, CICLO_FACT
	, CORREO_CLIENTE_PR
	, TELEFONO_CLIENTE_PR
	, IMEI
	, ORDEN
	, TIPO_MOVIMIENTO_MES
	, FECHA_MOVIMIENTO_MES
	, ES_PARQUE
	, BANCO
	, A.FECHA AS FECHA_ALTA_HISTORICA
	, A.CANAL AS CANAL_ALTA
	, A.SUB_CANAL AS SUB_CANAL_ALTA
	, A.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_ALTA
	, A.DISTRIBUIDOR AS DISTRIBUIDOR_ALTA
	, A.OFICINA AS OFICINA_ALTA
	, PORTABILIDAD
	, OPERADORA_ORIGEN
	, OPERADORA_DESTINO
	, MOTIVO
	, C.FECHA AS FECHA_PRE_POS
	, C.CANAL AS CANAL_PRE_POS
	, C.SUB_CANAL AS SUB_CANAL_PRE_POS
	, C.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_PRE_POS
	, C.DISTRIBUIDOR AS DISTRIBUIDOR_PRE_POS
	, C.OFICINA AS OFICINA_PRE_POS
	, D.FECHA AS FECHA_POS_PRE
	, D.CANAL AS CANAL_POS_PRE
	, D.SUB_CANAL AS SUB_CANAL_POS_PRE
	, D.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_POS_PRE
	, D.DISTRIBUIDOR AS DISTRIBUIDOR_POS_PRE
	, D.OFICINA AS OFICINA_POS_PRE
	, E.FECHA AS FECHA_CAMBIO_PLAN
	, E.CANAL AS CANAL_CAMBIO_PLAN
	, E.SUB_CANAL AS SUB_CANAL_CAMBIO_PLAN
	, E.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_CAMBIO_PLAN
	, E.DISTRIBUIDOR AS DISTRIBUIDOR_CAMBIO_PLAN
	, E.OFICINA AS OFICINA_CAMBIO_PLAN
	, COD_PLAN_ANTERIOR
	, DES_PLAN_ANTERIOR
	, TB_DESCUENTO
	, TB_OVERRIDE
	, DELTA
FROM
	{vTPivotParq} AS Z
LEFT JOIN {vTMP06} AS A
ON
	(NUM_TELEFONICO = A.TELEFONO)
LEFT JOIN {vTMP09} AS C
ON
	(NUM_TELEFONICO = C.TELEFONO)
	AND (LINEA_NEGOCIO_HOMOLOGADO <> 'PREPAGO')
LEFT JOIN {vTMP08} AS D
ON
	(NUM_TELEFONICO = D.TELEFONO)
	AND (LINEA_NEGOCIO_HOMOLOGADO = 'PREPAGO')
LEFT JOIN {vTMP10} AS E
ON
	(NUM_TELEFONICO = E.TELEFONO)
	AND (LINEA_NEGOCIO_HOMOLOGADO <> 'PREPAGO')
    '''.format(vTPivotParq=vTPivotParq, vTMP06=vTMP06, vTMP08=vTMP08, vTMP09=vTMP09, vTMP10=vTMP10)
    return qry



# N12
def qry_otc_t_360_parque_1_mov_mes_tmp(f_inicio, fecha_proceso, vTMP06, vTMP07, vTMP08, vTMP09, vTMP10):
    qry='''
SELECT
	TIPO
	, TELEFONO
	, FECHA AS FECHA_MOVIMIENTO_MES
	, CANAL AS CANAL_MOVIMIENTO_MES
	, SUB_CANAL AS SUB_CANAL_MOVIMIENTO_MES
	, NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_MOVIMIENTO_MES
	, DISTRIBUIDOR AS DISTRIBUIDOR_MOVIMIENTO_MES
	, OFICINA AS OFICINA_MOVIMIENTO_MES
	, PORTABILIDAD AS PORTABILIDAD_MOVIMIENTO_MES
	, OPERADORA_ORIGEN AS OPERADORA_ORIGEN_MOVIMIENTO_MES
	, OPERADORA_DESTINO AS OPERADORA_DESTINO_MOVIMIENTO_MES
	, MOTIVO AS MOTIVO_MOVIMIENTO_MES
	, COD_PLAN_ANTERIOR AS COD_PLAN_ANTERIOR_MOVIMIENTO_MES
	, DES_PLAN_ANTERIOR AS DES_PLAN_ANTERIOR_MOVIMIENTO_MES
	, TB_DESCUENTO AS TB_DESCUENTO_MOVIMIENTO_MES
	, TB_OVERRIDE AS TB_OVERRIDE_MOVIMIENTO_MES
	, DELTA AS DELTA_MOVIMIENTO_MES
FROM
	(
	SELECT
		TIPO
		, TELEFONO
		, FECHA
		, CANAL
		, SUB_CANAL
		, NUEVO_SUB_CANAL
		, DISTRIBUIDOR
		, OFICINA
		, PORTABILIDAD
		, OPERADORA_ORIGEN
		, OPERADORA_DESTINO
		, MOTIVO
		, COD_PLAN_ANTERIOR
		, DES_PLAN_ANTERIOR
		, TB_DESCUENTO
		, TB_OVERRIDE
		, DELTA
		, ROW_NUMBER() OVER (PARTITION BY TELEFONO
	ORDER BY
		FECHA DESC) AS RNUM
	FROM
		(
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, CAST( NULL AS STRING) AS PORTABILIDAD
			, CAST( NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST( NULL AS STRING) AS OPERADORA_DESTINO
			, CAST( NULL AS STRING) AS MOTIVO
			, COD_PLAN_ANTERIOR
			, DES_PLAN_ANTERIOR
			, TB_DESCUENTO
			, TB_OVERRIDE
			, DELTA
		FROM
			{vTMP10}
		WHERE
			FECHA BETWEEN '{f_inicio}' AND '{fecha_proceso}'
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, CAST( NULL AS STRING) AS PORTABILIDAD
			, CAST( NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST( NULL AS STRING) AS OPERADORA_DESTINO
			, CAST( NULL AS STRING) AS MOTIVO
			, CAST( NULL AS STRING) AS COD_PLAN_ANTERIOR
			, CAST( NULL AS STRING) AS DES_PLAN_ANTERIOR
			, CAST( NULL AS DOUBLE) AS TB_DESCUENTO
			, CAST( NULL AS DOUBLE) AS TB_OVERRIDE
			, CAST( NULL AS DOUBLE) AS DELTA
		FROM
			{vTMP08}
		WHERE
			FECHA BETWEEN '{f_inicio}' AND '{fecha_proceso}'
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, CAST( NULL AS STRING) AS PORTABILIDAD
			, CAST( NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST( NULL AS STRING) AS OPERADORA_DESTINO
			, CAST( NULL AS STRING) AS MOTIVO
			, CAST( NULL AS STRING) AS COD_PLAN_ANTERIOR
			, CAST( NULL AS STRING) AS DES_PLAN_ANTERIOR
			, CAST( NULL AS DOUBLE) AS TB_DESCUENTO
			, CAST( NULL AS DOUBLE) AS TB_OVERRIDE
			, CAST( NULL AS DOUBLE) AS DELTA
		FROM
			{vTMP09}
		WHERE
			FECHA BETWEEN '{f_inicio}' AND '{fecha_proceso}'
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, PORTABILIDAD
			, PERADORA_ORIGEN
			, OPERADORA_DESTINO
			, MOTIVO
			, CAST( NULL AS STRING) AS COD_PLAN_ANTERIOR
			, CAST( NULL AS STRING) AS DES_PLAN_ANTERIOR
			, CAST( NULL AS DOUBLE) AS TB_DESCUENTO
			, CAST( NULL AS DOUBLE) AS TB_OVERRIDE
			, CAST( NULL AS DOUBLE) AS DELTA
		FROM
			{vTMP07}
		WHERE
			FECHA BETWEEN '{f_inicio}' AND '{fecha_proceso}'
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, PORTABILIDAD
			, OPERADORA_ORIGEN
			, OPERADORA_DESTINO
			, MOTIVO
			, CAST( NULL AS STRING) AS COD_PLAN_ANTERIOR
			, CAST( NULL AS STRING) AS DES_PLAN_ANTERIOR
			, CAST( NULL AS DOUBLE) AS TB_DESCUENTO
			, CAST( NULL AS DOUBLE) AS TB_OVERRIDE
			, CAST( NULL AS DOUBLE) AS DELTA
		FROM
			{vTMP06}
		WHERE
			FECHA BETWEEN '{f_inicio}' AND '{fecha_proceso}' 
) ZZ ) TT
WHERE
	RNUM = 1
    '''.format(f_inicio=f_inicio, fecha_proceso=fecha_proceso, vTMP06=vTMP06, vTMP07=vTMP07, vTMP08=vTMP08, vTMP09=vTMP09, vTMP10=vTMP10)
    return qry


# N13
def qry_otc_t_360_parque_1_mov_seg_tmp(vTMP06, vTMP08, vTMP09):
    qry='''
	SELECT
	TIPO AS ORIGEN_ALTA_SEGMENTO
	, TELEFONO
	, FECHA AS FECHA_ALTA_SEGMENTO
	, CANAL AS CANAL_ALTA_SEGMENTO
	, SUB_CANAL AS SUB_CANAL_ALTA_SEGMENTO
	, NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_ALTA_SEGMENTO
	, DISTRIBUIDOR AS DISTRIBUIDOR_ALTA_SEGMENTO
	, FICINA AS OFICINA_ALTA_SEGMENTO
	, PORTABILIDAD AS PORTABILIDAD_ALTA_SEGMENTO
	, OPERADORA_ORIGEN AS OPERADORA_ORIGEN_ALTA_SEGMENTO
	, OPERADORA_DESTINO AS OPERADORA_DESTINO_ALTA_SEGMENTO
	, MOTIVO AS MOTIVO_ALTA_SEGMENTO
FROM
	(
	SELECT
		TIPO
		, TELEFONO
		, FECHA
		, CANAL
		, SUB_CANAL
		, NUEVO_SUB_CANAL
		, DISTRIBUIDOR
		, OFICINA
		, PORTABILIDAD
		, OPERADORA_ORIGEN
		, OPERADORA_DESTINO
		, MOTIVO
		, ROW_NUMBER() OVER (PARTITION BY TELEFONO
	ORDER BY
		FECHA DESC) AS RNUM
	FROM
		(
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, CAST( NULL AS STRING) AS PORTABILIDAD
			, CAST( NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST( NULL AS STRING) AS OPERADORA_DESTINO
			, CAST( NULL AS STRING) AS MOTIVO
		FROM
			{vTMP08}
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, CAST( NULL AS STRING) AS PORTABILIDAD
			, CAST( NULL AS STRING) AS OPERADORA_ORIGEN
			, CAST( NULL AS STRING) AS OPERADORA_DESTINO
			, CAST( NULL AS STRING) AS MOTIVO
		FROM
			{vTMP09}
	UNION ALL
		SELECT
			TIPO
			, TELEFONO
			, FECHA
			, CANAL
			, SUB_CANAL
			, NUEVO_SUB_CANAL
			, DISTRIBUIDOR
			, OFICINA
			, PORTABILIDAD
			, OPERADORA_ORIGEN
			, OPERADORA_DESTINO
			, MOTIVO
		FROM
			{vTMP06}
) ZZ ) TT
WHERE
	RNUM = 1
    '''.format(vTMP06=vTMP06, vTMP08=vTMP08, vTMP09=vTMP09)
    return qry


# N14
def qry_otc_t_360_parque_1_tmp_t_mov_mes(vTPivotParq, vTMP12):
    qry='''
SELECT
	NUM_TELEFONICO
	, CODIGO_PLAN
	, FECHA_ALTA
	, FECHA_LAST_STATUS
	, ESTADO_ABONADO
	, FECHA_PROCESO
	, NUMERO_ABONADO
	, LINEA_NEGOCIO
	, ACCOUNT_NUM
	, SUB_SEGMENTO
	, TIPO_DOC_CLIENTE
	, IDENTIFICACION_CLIENTE
	, CLIENTE
	, CUSTOMER_REF
	, COUNTED_DAYS
	, LINEA_NEGOCIO_HOMOLOGADO
	, CATEGORIA_PLAN
	, TARIFA
	, NOMBRE_PLAN
	, MARCA
	, CICLO_FACT
	, CORREO_CLIENTE_PR
	, TELEFONO_CLIENTE_PR
	, IMEI
	, ORDEN
	, TIPO_MOVIMIENTO_MES
	, B.FECHA_MOVIMIENTO_MES
	, ES_PARQUE
	, BANCO
	, CANAL_MOVIMIENTO_MES
	, SUB_CANAL_MOVIMIENTO_MES
	, NUEVO_SUB_CANAL_MOVIMIENTO_MES
	, DISTRIBUIDOR_MOVIMIENTO_MES
	, OFICINA_MOVIMIENTO_MES
	, PORTABILIDAD_MOVIMIENTO_MES
	, OPERADORA_ORIGEN_MOVIMIENTO_MES
	, OPERADORA_DESTINO_MOVIMIENTO_MES
	, MOTIVO_MOVIMIENTO_MES
	, COD_PLAN_ANTERIOR_MOVIMIENTO_MES
	, DES_PLAN_ANTERIOR_MOVIMIENTO_MES
	, TB_DESCUENTO_MOVIMIENTO_MES
	, TB_OVERRIDE_MOVIMIENTO_MES
	, DELTA_MOVIMIENTO_MES
FROM
	{vTPivotParq} AS B
LEFT JOIN {vTMP12} AS A
ON
	(NUM_TELEFONICO = A.TELEFONO)
	AND B.FECHA_MOVIMIENTO_MES = A.FECHA_MOVIMIENTO_MES
    '''.format(vTPivotParq=vTPivotParq, vTMP12=vTMP12)
    return qry



