--PARAMETROS PARA LA ENTIDAD OTC_T_360_UBICACION
DELETE FROM params WHERE entidad='OTC_T_360_UBICACION';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','HIVEDB','db_reportes','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','HIVETABLE','otc_t_360_ubicacion','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','RUTA','/RGenerator/reportes/Cliente360','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','SHELL','/RGenerator/reportes/Cliente360/Bin/OTC_T_360_UBICACION.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','RUTA_LOG','/RGenerator/reportes/Cliente360/Log','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','ETAPA','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','RUTA_PYTHON','/RGenerator/reportes/Cliente360/Python','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','TABLA_MKSHAREVOZDATOS_90','db_ipaccess.mksharevozdatos_90','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','VAL_ETP01_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','VAL_ETP01_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','VAL_ETP01_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','VAL_ETP01_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','VAL_ETP02_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','VAL_ETP02_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','VAL_ETP02_EXECUTOR_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','VAL_ETP02_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_UBICACION','VAL_ETP02_NUM_EXECUTORS_CORES','8','0','1');
SELECT * FROM params WHERE entidad='OTC_T_360_UBICACION';


---PARAMETROS PARA LA ENTIDAD OTC_T_360_PARQUE_TRAFICADOR

DELETE FROM params WHERE entidad='OTC_T_360_PARQUE_TRAFICADOR';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','RUTA','/RGenerator/reportes/Cliente360','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','SHELL','/RGenerator/reportes/Cliente360/Bin/OTC_T_360_PARQUE_TRAFICADOR.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','RUTA_LOG','/RGenerator/reportes/Cliente360/Log','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','RUTA_PYTHON','/RGenerator/reportes/Cliente360/Python','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','VAL_ESQUEMA_TMP','db_temporales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','vTPPCSLlamadas','db_altamira.otc_t_ppcs_llamadas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','vTDevCatPlan','db_reportes.otc_t_dev_cat_plan','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','vTPPCSDiameter','db_altamira.otc_t_ppcs_diameter','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','vTPPCSMecooring','db_altamira.otc_t_ppcs_mecoorig','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','vTPPCSContent','db_altamira.otc_t_ppcs_content','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','VAL_ETP01_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','VAL_ETP01_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','VAL_ETP01_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','VAL_ETP01_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PARQUE_TRAFICADOR','ETAPA','1','0','1');
SELECT * FROM params WHERE entidad='OTC_T_360_PARQUE_TRAFICADOR';





---PARAMETROS PARA LA ENTIDAD OTC_T_360_PIVOT_PARQUE

DELETE FROM params WHERE entidad='OTC_T_360_PIVOT_PARQUE';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','HIVEDB','db_temporales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ESQUEMA_TMP','db_temporales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','HIVETABLE','otc_t_360_parque_1_tmp','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','RUTA','/RGenerator/reportes/Cliente360','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','SHELL','/RGenerator/reportes/Cliente360/Bin/OTC_T_360_PIVOT_PARQUE.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','RUTA_LOG','/RGenerator/reportes/Cliente360/Log','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','ETAPA','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','RUTA_PYTHON','/RGenerator/reportes/Cliente360/Python','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','vTAltasBi','db_cs_altas.otc_t_altas_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','vTTransferOutBi','db_cs_altas.otc_t_transfer_out_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','vTTransferInBi','db_cs_altas.otc_t_transfer_in_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','vTCPBi','db_cs_altas.otc_t_cambio_plan_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','vTBajasInv','db_cs_altas.otc_t_bajas_involuntarias','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','vTChurnSP2','db_cs_altas.otc_t_churn_sp2','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','vTCFact','db_rbm.otc_t_vw_cta_facturacion','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','vTPRMANDATE','db_rbm.otc_t_prmandate','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','vTBajasBi','db_cs_altas.otc_t_bajas_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','vTRiMobPN','db_rdb.otc_t_r_ri_mobile_phone_number','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP01_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP01_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP01_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP01_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP02_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP02_DRIVER_MEMORY','2G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP02_EXECUTOR_MEMORY','2G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP02_NUM_EXECUTORS','80','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP02_NUM_EXECUTORS_CORES','3','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP03_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP03_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP03_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP03_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP03_NUM_EXECUTORS_CORES','8','0','1');
SELECT * FROM params WHERE entidad='OTC_T_360_PIVOT_PARQUE';


---PARAMETROS PARA LA ENTIDAD OTC_T_360_RECARGAS

DELETE FROM params WHERE entidad='OTC_T_360_RECARGAS';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','HIVEDB','db_temporales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','VAL_ESQUEMA_TMP','db_temporales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','HIVETABLE','tmp_otc_t_360_recargas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','RUTA','/RGenerator/reportes/Cliente360','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','SHELL','/RGenerator/reportes/Cliente360/Bin/OTC_T_360_RECARGAS.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','RUTA_LOG','/RGenerator/reportes/Cliente360/Log','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','ETAPA','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','RUTA_PYTHON','/RGenerator/reportes/Cliente360/Python','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','vTDetRecarg','db_cs_recargas.otc_t_cs_detalle_recargas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','vTParOriRecarg','db_altamira.par_origen_recarga','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','vTCatBonosPdv','db_reportes.cat_bonos_pdv','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','VAL_ETP01_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','VAL_ETP01_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','VAL_ETP01_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','VAL_ETP01_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_RECARGAS','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','1');
SELECT * FROM params WHERE entidad='OTC_T_360_RECARGAS';


---PARAMETROS PARA LA ENTIDAD OTC_T_360_MOVIMIENTOS_PARQUE

DELETE FROM params WHERE entidad='OTC_T_360_MOVIMIENTOS_PARQUE';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','RUTA','/RGenerator/reportes/Cliente360','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','SHELL','/RGenerator/reportes/Cliente360/Bin/OTC_T_360_MOVIMIENTOS_PARQUE.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','RUTA_LOG','/RGenerator/reportes/Cliente360/Log','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','RUTA_PYTHON','/RGenerator/reportes/Cliente360/Python','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ESQUEMA_TMP','db_temporales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ESQUEMA_REP','db_reportes','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTAltBajHist','db_reportes.otc_t_alta_baja_hist','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTAltBI','db_cs_altas.otc_t_altas_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTBajBI','db_cs_altas.otc_t_bajas_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTTransfHist','db_reportes.otc_t_transfer_hist','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTTrInBI','db_cs_altas.otc_t_transfer_in_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTTrOutBI','db_cs_altas.otc_t_transfer_out_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTCPHist','db_reportes.otc_t_cambio_plan_hist','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTCPBI','db_cs_altas.otc_t_cambio_plan_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTNRHist','db_reportes.otc_t_no_reciclable_hist','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTNRCSA','db_cs_altas.no_reciclable','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTABRHist','db_reportes.otc_t_alta_baja_reproceso_hist','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTCatPosUsr','db_cs_altas.otc_t_ctl_pos_usr_nc','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTPivotParq','db_temporales.otc_t_360_parque_1_tmp','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','1');

INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','ETAPA','1','0','1');
SELECT * FROM params WHERE entidad='OTC_T_360_MOVIMIENTOS_PARQUE';


--PARAMETROS PARA LA ENTIDAD D_OTC_T_360_RTD
DELETE FROM params_des WHERE entidad='D_OTC_T_360_RTD';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','HIVEDB','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','HIVETABLE','otc_t_rtd_oferta_sugerida_pryclr','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','RUTA','/home/nae108400/2023/Cloudera/RGenerator/reportes/Cliente360','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','SHELL','/home/nae108400/2023/Cloudera/RGenerator/reportes/Cliente360/Bin/OTC_T_360_RTD.sh','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','TDDB','STAGING','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','TDHOST','fulldb-scan.otecel.com.ec','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','TDPASS','rtdm_stag','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','TDTABLE','stg_cliente_360_pryclr','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','TDUSER','STAGING','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','RUTA_LOG','/home/nae108400/2023/Cloudera/RGenerator/reportes/Cliente360/Log','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','TDPORT','7594','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','TDSERVICE','sasdb.otecel.com.ec','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','ETAPA','1','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','RUTA_PYTHON','/home/nae108400/2023/Cloudera/RGenerator/reportes/Cliente360/Python','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','RUTA_LIB','/home/nae108400/2023/Cloudera/RGenerator/reportes/Cliente360/lib','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','RUTA_LIB_ORACLE','ojdbc6-11.2.0.4.jar','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ESQUEMA_TMP','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','TABLA_PIVOTANTE','db_temporales.otc_t_360_parque_1_tmp','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','COMBO_DEFECTO','COMBO 1','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ETP01_MASTER','yarn','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ETP01_DRIVER_MEMORY','16G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ETP01_EXECUTOR_MEMORY','16G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ETP01_NUM_EXECUTORS','8','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ETP02_MASTER','local','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ETP02_DRIVER_MEMORY','16G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ETP02_EXECUTOR_MEMORY','32G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ETP02_NUM_EXECUTORS','8','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_360_RTD','VAL_ETP02_NUM_EXECUTORS_CORES','8','0','0');
SELECT * FROM params_des WHERE entidad='D_OTC_T_360_RTD';