--PARAMETROS PARA LA ENTIDAD OTC_T_360_PIVOT_PARQUE
DELETE FROM params WHERE entidad='OTC_T_360_PIVOT_PARQUE';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','HIVEDB','db_desarrollo2021','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','HIVETABLE','OTC_T_360_PIVOT_PARQUE','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','RUTA','/RGenerator/reportes/Cliente360','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','SHELL','/RGenerator/reportes/Cliente360/Bin/OTC_T_360_PIVOT_PARQUE.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','RUTA_LOG','/RGenerator/reportes/Cliente360/Log','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','ETAPA','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','RUTA_PYTHON','/RGenerator/reportes/Cliente360/Python','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','TABLA_MKSHAREVOZDATOS_90','db_ipaccess.mksharevozdatos_90','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP01_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP01_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP01_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP01_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP01_NUM_EXECUTORS_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP02_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP02_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP02_EXECUTOR_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP02_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_PIVOT_PARQUE','VAL_ETP02_NUM_EXECUTORS_CORES','8','0','1');
SELECT * FROM params WHERE entidad='OTC_T_360_PIVOT_PARQUE';

